name: Upload File to Branch

on:
  workflow_dispatch:  # Allows manual triggering of this action
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create or switch to data-branch
        id: create_branch
        run: |
          # Check if the branch already exists
          if git rev-parse --verify origin/data-branch; then
            echo "Branch already exists."
            git checkout data-branch
          else
            echo "Creating new branch data-branch."
            git checkout -b data-branch
          fi

      - name: Add file
        run: |
          mkdir -p data
          echo "This is an example file content." > data/myfile.txt
          git add data/myfile.txt
          git commit -m "Add or update data/myfile.txt"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin data-branch

