name: Upload File to Storage Branch

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to the latest version
        with:
          fetch-depth: 0  # Ensures all history is fetched for debugging

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '20'  # Set to Node.js 20
        id: node

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          npm list --depth=0  # List installed dependencies for debugging

      - name: Run upload.js script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Access the secret here
        run: |
          echo "Running upload.js script"
          node upload.js

